# Generated by Django 4.2.6 on 2023-11-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey_question',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='survey_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('surveyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_app.survey_question')),
            ],
        ),
    ]
