name: Django Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect Static Files
        run: |
            cd survey_project
            python manage.py collectstatic --noinput

      - name: Migrate Database
        run: python manage.py migrate

      - name: Restart Gunicorn (Assuming you are using Gunicorn as your server)
        run: sudo systemctl restart gunicorn.service

      # Add any additional steps for your deployment process

      # You might need to restart your web server or perform other actions based on your setup.

