name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Vinithk1234$
          POSTGRES_DB: CRUD_survey
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Django
          python -m pip install psycopg2-binary

      - name: Wait for database to be ready
        run: |
          # Implement a script or use wait-for-it.sh to wait for the database

      - name: Activate virtual environment
        run: |
          source newvenv/Scripts/activate  # Change for Unix-like systems
          # OR
          # call newvenv\Scripts\activate  # Change for Windows

      - name: Run database migrations
        run: |
          cd survey_project
          python manage.py makemigrations
          python manage.py migrate --noinput

      - name: Collect static files
        run: |
          cd survey_project
          
          python manage.py collectstatic --noinput

      - name: Install Gunicorn
        run: |
          python -m pip install gunicorn

      - name: Run Django application using Gunicorn
        run: |
          cd survey_project
          gunicorn  survey_project.wsgi:application
