name: Django project
run-name: Django_deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y postgresql
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'Vinithk1234'"
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Make migrations
        run: |
          cd survey_project
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Django server
        run: |
          cd survey_project
          python manage.py runserver 0:8000
