name: Django Deployment

on:
  push:    
    branches:     
      - main

jobs:      
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Vinithk1234$
          #POSTGRES_HOST: localhost
          POSTGRES_DB: CRUD_survey
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Django
          python -m pip install psycopg2
          #pip install -r requirements.txt

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install
          sudo apt-get install postgresql 
          

          sudo service postgresql start

      - name: Activate virtual environment
        run: |
            source newvenv/Scripts/activate

      - name: Run database migrations
        run: |
          cd survey_project          
          python manage.py makemigrations
          python manage.py migrate
          

      - name: Collect static files
        run: |
          cd survey_project
          python manage.py collectstatic --noinput
          

      - name: Install Gunicorn
        run: |
          python -m pip install gunicorn

      - name: Run Django application using Gunicorn
        run: |
          cd survey_project
          gunicorn --bind 0.0.0.0:5001 survey_project.wsgi:application 
          
  
