name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Django

          pip install -r requirements.txt

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql
          sudo service postgresql start
       
      - name: Activate virtual environment
        run: |
          source newvenv/Scripts/activate
      - name: Run database migrations
        run: |
          cd survey_project
          python manage.py migrate

      - name: Run tests
        run: |
         cd survey_project
         python manage.py test

      - name: Deploy to production
        run: |
          # Add your deployment commands here
          # For example, you can use SSH to connect to your production server and deploy the project
