name: Django project
run-name: Django_deploy

on:
 push:
   branches: ["main"]
 pull_request:
    branches: ["main"]

jobs:
  builder:
     runs-on: ubuntu-latest
     strategy:
        max-parallel: 4
        matrix:
          python-version: [3.10,3.11,3.12]
     steps:
     - uses: python/check-out@v3
     - name: Set-up python ${{matrix.python-version}}
     - uses: python/set-up@v3
       with:
           python-version: ${{matrix.python-verion}}
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
     - name: Run test
       run: |
     
   




  
  
  
 
 

