name: Django project
run-name: Django_deploy

on:
 push:
   branches: ["main"]
 pull_request:
    branches: ["main"]

jobs:
  build:
     runs-on: ubuntu-latest
     strategy:
        max-parallel: 4
        matrix:
          python-version: [3.11]
     steps:
     - uses: python/checkout@v2
     - name: Set-up python ${{matrix.python-version}}
     - uses: python/setup-python@v1
       with:
           python-version: ${{matrix.python-verion}}
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         py -m pip install -r requirements.txt
     - name: Run test
       run: |
         python manage.py test
   




  
  
  
 
 

