name: Django Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_NAME: 'CRUD_survey'
      DB_USER: 'postgres'
      DB_PASSWORD: 'Vinithk1234$'
      DB_HOST: 'localhost'
      DB_PORT: '5432'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Postgresql setuo    
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Environment Variables
        run: |
          echo "export DB_NAME=DB_NAME" >> $GITHUB_ENV
          echo "export DB_USER=DB_USER" >> $GITHUB_ENV
          echo "export DB_PASSWORD=DB_PASSWORD" >> $GITHUB_ENV
          echo "export DB_HOST=DB_HOST" >> $GITHUB_ENV
          echo "export DB_PORT=DB_PORT" >> $GITHUB_ENV
      - name: Collect Static Files
        run: |
          cd survey_project
          python manage.py collectstatic --noinput

      - name: Migrate Database
        run: |
          cd survey_project
          python manage.py migrate

      - name: Restart Gunicorn (Assuming you are using Gunicorn as your server)
        run: sudo systemctl restart gunicorn.service

