name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Vinithk1234$
          POSTGRES_DB: CRUD_survey
          
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Django

          pip install -r requirements.txt

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install 

          sudo service postgresql start

      - name: Activate virtual environment
        run: |
          sudo systemctl status postgresql
          sudo systemctl start postgresql

          source newvenv/Scripts/activate

      - name: Run database migrations
        run: |
          cd survey_project          
          python manage.py migrate

      - name: Collect static files
        run: |
          cd survey_project
          python manage.py collectstatic --noinput

      - name: Install Gunicorn
        run: |
          python -m pip install gunicorn

      - name: Run Django application using Gunicorn
        run: |
          cd survey_project
          gunicorn survey_project.wsgi:application

      # Optional: You can add additional steps for database backups, environment setup, etc.
