name: Django Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: "survey_project.settings"  # Set your Django settings module here
      SECRET_KEY: django-insecure--dg7-bc48jm1&p2c1y6p_%y*j!&qzjk3xz1-k!yy@-z5r4b0u3  # Store your secret key in GitHub Secrets

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect Static Files
        run: |
          cd survey_project
          python manage.py collectstatic --noinput

      - name: Migrate Database
        run: |
          cd survey_project
          python manage.py migrate

      - name: Restart Gunicorn (Assuming you are using Gunicorn as your server)
        run: sudo systemctl restart gunicorn.service

